/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "biegmtgijxitiqydzhdk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZWdtdGdpanhpdGlxeWR6aGRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0MjkyMjMsImV4cCI6MjA3NjAwNTIyM30.EEz3dVACm83dGdR0og41HhbA-9BVWlJ9-nhVwywZbhY"